name: Stock Scanner

on:
  schedule:
    - cron: '*/15 13-20 * * 1-5'  # ⏰ ตลาด US
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install libs
        run: pip install -r requirements.txt

      - name: Run Scanner
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python scanner_us_stocks.py
