name: Stock Scanner

on:
  schedule:
    - cron: '*/1 13-20 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - name: Run Scanner
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python scanner_us_stocks.py
